[container.image]
repository="xlight05"
name="inventory_app"
tag="0.1.0"

[[cloud.config.files]]
file="./Configs.toml"

[[cloud.config.secrets]]
file="./Secrets.toml"

[cloud.deployment]
min_memory="512Mi"
max_memory="1Gi"
min_cpu="250m"
max_cpu="500m"

[cloud.deployment.autoscaling]
min_replicas=2
max_replicas=5
cpu=70
memory=80

[cloud.deployment.probes.liveness]
port=9090
path="/store/liveness"

[cloud.deployment.probes.readiness]
port=9090
path="/store/readiness"
