## Service
apiVersion: v1
kind: Service
metadata:
  name: mysql8-service
  labels:
    app: mysql8
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql8
---
## Initialization script storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: init-script-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
---
## MySQL data storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql8
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql8
        logs: "true"
    spec:
      initContainers:
        - name: init-script-downloader
          image: appropriate/curl
          args:
            - "-o"
            - "/tmp/data/init.sql"
            - "https://gist.githubusercontent.com/xlight05/d5400ee2d230144149b787f2312f3225/raw/337e6aa9e6bb56861cf6838bb149258e2f862fcd/init.sql"
          volumeMounts:
            - name: init-script
              mountPath: /tmp/data
      containers:
        - name: mysql8
          image: mysql:8.0.33
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec mysqladmin ping -h localhost -u root -p password
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: init-script
          persistentVolumeClaim:
            claimName: init-script-pvc
        - name: data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
---
